using System;
using TheXDS.Ganymede.Component;

namespace TheXDS.Ganymede.Services;

/// <summary>
/// Implements a dialog service that provides of some basic UI services for
/// user interaction. 
/// </summary>
public partial class DialogService
{
    /// <summary>
    /// Gets a reference to the <see cref="UiPresenter"/> used to display the
    /// View for any dialogs generated by this instance.
    /// </summary>
    public UiPresenter Content { get; } = new();
}
