//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ganymede.Wpf.Playground.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WelcomeView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WelcomeView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ganymede.Wpf.Playground.Resources.Strings.Views.WelcomeView", typeof(WelcomeView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs demo.
        /// </summary>
        public static string DialogsDemo {
            get {
                return ResourceManager.GetString("DialogsDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page will guide you through Ganymede, the MVVM navigation and UI framework.
        ///
        ///Ganymede is an MVVM app-template framework that provides infrastructure for building cross-platform desktop applications using XAML-based UI frameworks. The framework eliminates boilerplate code by providing pre-built implementations of navigation services, dialog services, base ViewModel classes, command builders, and common entry points. Developers provide their ViewModels and Views while Ganymede handles auxiliary UI serv [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to new page.
        /// </summary>
        public static string NavToNewPage {
            get {
                return ResourceManager.GetString("NavToNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test busy state.
        /// </summary>
        public static string TestBusy {
            get {
                return ResourceManager.GetString("TestBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganymede Demo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
