//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Ganymede.Resources.Strings.Models; 
using System;


/// <summary>
///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
/// </summary>
// StronglyTypedResourceBuilder generó automáticamente esta clase
// a través de una herramienta como ResGen o Visual Studio.
// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
// con la opción /str o recompile su proyecto de VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
public class User {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal User() {
    }
    
    /// <summary>
    ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Ganymede.Resources.Strings.Models.User", typeof(User).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
    ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Busca una cadena traducida similar a User description.
    /// </summary>
    public static string Description {
        get {
            return ResourceManager.GetString("Description", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Busca una cadena traducida similar a Display name.
    /// </summary>
    public static string DisplayName {
        get {
            return ResourceManager.GetString("DisplayName", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Busca una cadena traducida similar a Is user enabled.
    /// </summary>
    public static string Enabled {
        get {
            return ResourceManager.GetString("Enabled", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Busca una cadena traducida similar a User name.
    /// </summary>
    public static string Id {
        get {
            return ResourceManager.GetString("Id", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Busca una cadena traducida similar a Password.
    /// </summary>
    public static string Password {
        get {
            return ResourceManager.GetString("Password", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Busca una cadena traducida similar a User.
    /// </summary>
    public static string UserModel {
        get {
            return ResourceManager.GetString("UserModel", resourceCulture);
        }
    }
}
